config/routes.rb
Rails.application.routes.draw do
  resources :exam_types
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exam_type.rb
class ExamType < ApplicationRecord
  enum status: {created: 0, approved: 1}

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exam_types_controller.rb
class ExamTypesController < ApplicationController
  before_action :set_exam_type, only: %i[ show edit update destroy ]

  # GET /exam_types or /exam_types.json
  def index
    @exam_types = ExamType.ordered
  end

  # GET /exam_types/1 or /exam_types/1.json
  def show
  end

  # GET /exam_types/new
  def new
    @exam_type = ExamType.new
  end

  # GET /exam_types/1/edit
  def edit
  end

  # POST /exam_types or /exam_types.json
  def create
    @exam_type = ExamType.new(exam_type_params)

    if @exam_type.save
      flash.now[:notice] = "Exam Type was successfully created."

      render turbo_stream: [
        turbo_stream.prepend("exam_types", @exam_type),
        turbo_stream.update(ExamType.new, ""),
        turbo_stream.prepend("flash", partial: "layouts/flash")
      ]
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /exam_types/1 or /exam_types/1.json
  def update
    if @exam_type.update(exam_type_params)
      flash.now[:notice] = "Exam Type was successfully updated."

      render turbo_stream: [
        turbo_stream.replace(@exam_type, @exam_type),
        turbo_stream.prepend("flash", partial: "layouts/flash")
      ]
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /exam_types/1 or /exam_types/1.json
  def destroy
    @exam_type.destroy
    flash.now[:notice] = "Exam Type was successfully destroyed."

    render turbo_stream: [
      turbo_stream.remove(@exam_type),
      turbo_stream.prepend("flash", partial: "layouts/flash")
    ]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exam_type
      @exam_type = ExamType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exam_type_params
      params.require(:exam_type).permit(:name, :status)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exam_types_helper.rb
module ExamTypesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/exam_types/_exam_type.html.erb
<%= turbo_frame_tag exam_type do %>
  <div class="table min-w-full">
    <div><%= link_to exam_type.name, exam_type_path(exam_type), data: { turbo: false } %></div>
    <div><%= exam_type.status %></div>
    <div>
      <% if action_name != "show" %>
        <%= link_to edit_exam_type_path(exam_type) do %>
          <svg class="inline-block w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
        <% end %>
        <%= button_to exam_type_path(exam_type), method: :delete, form_class: "inline-block ml-4" do %>
          <svg class="inline-block w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/exam_types/_form.html.erb
<%= form_with model: exam_type, id: dom_id(exam_type, "form"), class: "table min-w-full" do |form| %>
  <% if exam_type.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(exam_type.errors.count, "error") %> prohibited this exam_type from being saved:</h2>

      <ul>
        <% exam_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.select :status, ExamType.statuses.keys %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/exam_types/edit.html.erb
<%= turbo_frame_tag @exam_type, class: "w-full" do %>
  <%= render "form", exam_type: @exam_type %>
<% end %>

app/views/exam_types/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Exam Types</h1>
    <%= link_to "New Exam Type",
                new_exam_type_path,
                class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium",
                data: {turbo_frame: dom_id(ExamType.new) } %>
  </div>

  <div class="min-w-full my-8">
    <div class="table font-bold min-w-full">
      <div>Name</div>
      <div>Status</div>
      <div></div>
    </div>

    <%= turbo_frame_tag ExamType.new %>

    <%= turbo_frame_tag "exam_types" do %>
      <div id="exam_types">
        <%= render @exam_types %>
      </div>
    <% end %>
  </div>
</div>

app/views/exam_types/new.html.erb
<%= turbo_frame_tag @exam_type, class: "w-full" do %>
  <%= render "form", exam_type: @exam_type %>
<% end %>

app/views/exam_types/show.html.erb
<div class="min-w-full">
  <div class="font-bold">Show:</div>
  <div>Name of the exam type:<%= @exam_type.name %></div>
  <div>Current status of the exam type:<%= @exam_type.status %></div>
</div>

app/views/home/index.html.erb
<h1 class="text-3xl font-bold underline">Welcome</h1>
<%= link_to 'Exam Type', exam_types_path %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="mx-auto md:w-2/3 w-full flex">
    <p class="mx-auto py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block"><%= message %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineExaminationSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
    
      <div id="flash" class="flash">
        <%= render "layouts/flash" %>
      </div>

      <%= yield %>
    </main>
  </body>
</html>